### PR TITLE
Basic infrastructure for system tests

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by remcobeckers** [comment]
Should this (in theory at least) also run the system tests on a Mac? I can now from this branch run the normal tests on my machine but for the system tests I get an error that seems to be related to the current working dir the beats test tool is expecting

**Comment by raboof** [comment]
TBQH I'm not sure - though of course it should be a step in that direction. Can you post the error?

**Comment by remcobeckers** [comment]
This is the entire output of `make testsuite`

```/Applications/Xcode.app/Contents/Developer/usr/bin/make unit-tests
mkdir -p /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build/coverage
# gotestcover is needed to fetch coverage for multiple packages
go get github.com/pierrre/gotestcover
/Volumes/Home/Users/remco/dev/go/bin/gotestcover  -coverprofile=/Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build/coverage/unit.cov  github.com/raboof/connbeat/...
?       github.com/raboof/connbeat/processes    [no test files]
?       github.com/raboof/connbeat      [no test files]
ok      github.com/raboof/connbeat/beater       0.325s  coverage: 43.8% of statements
# Setups environment if TEST_ENVIRONMENT is set to true
if [ false = true ]; then \
                 /Applications/Xcode.app/Contents/Developer/usr/bin/make integration-tests-environment; \
        else \
                /Applications/Xcode.app/Contents/Developer/usr/bin/make integration-tests; \
        fi
mkdir -p /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build/coverage
# gotestcover is needed to fetch coverage for multiple packages
go get github.com/pierrre/gotestcover
/Volumes/Home/Users/remco/dev/go/bin/gotestcover -tags=integration  -coverprofile=/Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build/coverage/integration.cov  github.com/raboof/connbeat/...
?       github.com/raboof/connbeat/processes    [no test files]
?       github.com/raboof/connbeat      [no test files]
ok      github.com/raboof/connbeat/beater       0.325s  coverage: 43.8% of statements
# Runs system tests if SYSTEM_TESTS is set to true
if [ false = true ]; then \
                if [ false = true ]; then \
                        docker-compose -f /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/../testing/environments/base.yml -f /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/../testing/environments/snapshot.yml -f docker-compose.yml run beat make system-tests; \
                else \
                        /Applications/Xcode.app/Contents/Developer/usr/bin/make system-tests; \
                fi \
        fi
/Applications/Xcode.app/Contents/Developer/usr/bin/make benchmark-tests
# No benchmark tests exist so far
#go test -bench=. github.com/raboof/connbeat/...
/Applications/Xcode.app/Contents/Developer/usr/bin/make coverage-report
python ../dev-tools/aggregate_coverage.py -o /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build/coverage/full.cov /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build/coverage
/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '../dev-tools/aggregate_coverage.py': [Errno 2] No such file or directory
make[1]: *** [coverage-report] Error 2
make: *** [testsuite] Error 2```

**Comment by remcobeckers** [comment]
And when I set TEST_ENVIRONMENT=true first a different yet similar error happens:
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make unit-tests
mkdir -p /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build/coverage
# gotestcover is needed to fetch coverage for multiple packages
go get github.com/pierrre/gotestcover
/Volumes/Home/Users/remco/dev/go/bin/gotestcover  -coverprofile=/Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build/coverage/unit.cov  github.com/raboof/connbeat/...
?       github.com/raboof/connbeat/processes    [no test files]
?       github.com/raboof/connbeat      [no test files]
ok      github.com/raboof/connbeat/beater       0.320s  coverage: 43.8% of statements
# Setups environment if TEST_ENVIRONMENT is set to true
if [ true = true ]; then \
                 /Applications/Xcode.app/Contents/Developer/usr/bin/make integration-tests-environment; \
        else \
                /Applications/Xcode.app/Contents/Developer/usr/bin/make integration-tests; \
        fi
/Applications/Xcode.app/Contents/Developer/usr/bin/make prepare-tests
mkdir -p /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build/coverage
# gotestcover is needed to fetch coverage for multiple packages
go get github.com/pierrre/gotestcover
/Applications/Xcode.app/Contents/Developer/usr/bin/make build-image
mkdir -p /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build
echo "ES_HOST="elasticsearch"" > /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build/test.env
echo "ES_PORT=9200" >> /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build/test.env
echo "ES_USER=beats" >> /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build/test.env
echo "ES_PASS=testing" >> /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/build/test.env
docker-compose -f /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/../testing/environments/base.yml -f /Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/../testing/environments/snapshot.yml -f docker-compose.yml build
ERROR: .IOError: [Errno 2] No such file or directory: '/Volumes/Home/Users/remco/dev/go/src/github.com/raboof/connbeat/../testing/environments/base.yml'
make[2]: *** [build-image] Error 1
make[1]: *** [integration-tests-environment] Error 2
make: *** [testsuite] Error 2
```

**Comment by remcobeckers** [comment]
And another strange thing is that SYSTEM_TESTS is true in my environment:
```>echo $SYSTEM_TESTS
true
```

**Comment by remcobeckers** [comment]
But it does run on Travis, so that is already nice! 👍

**Comment by raboof** [comment]
Interesting, it seems the environment settings from the main Makefile aren't propagated.

I'm using GNU Make, I seem to remember OSX ships BSD make? is there a 'gmake'?

**Comment by remcobeckers** [comment]
I'm using GNU make as well apparently:
```
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```
But this might be a really old version

**Comment by remcobeckers** [comment]
Installed `make` from brew which ends up as `gmake` (and is gnu make v4.2). Same result...

**Comment by remcobeckers** [comment]
Do you still want to merge this? If it works on Linux it is good enough for me right now.

**Comment by raboof** [comment]
As it does run on travis I think that'd still be useful - but it looks like I have some merge problems to solve :)

**Pull request merged**
